import type { Run, SSEEvent } from './types'

export const MOCK_RUNS: Run[] = [
  {
    id: 'run-001',
    issue_number: 42,
    issue_title: 'Add dark mode toggle to settings page',
    repo: 'acme/webapp',
    status: 'running',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    started_at: new Date(Date.now() - 4 * 60_000).toISOString(),
    turns: 7,
  },
  {
    id: 'run-002',
    issue_number: 87,
    issue_title: 'Fix pagination offset bug in /api/users',
    repo: 'acme/webapp',
    status: 'awaiting_approval',
    provider: 'openai',
    model: 'gpt-4o',
    started_at: new Date(Date.now() - 12 * 60_000).toISOString(),
    turns: 14,
    test_result: 'passed',
    pr_url: 'https://github.com/acme/webapp/pull/88',
  },
  {
    id: 'run-003',
    issue_number: 53,
    issue_title: 'Refactor auth middleware to use JWT',
    repo: 'acme/api-server',
    status: 'done',
    provider: 'gemini',
    model: 'gemini-2.5-pro',
    started_at: new Date(Date.now() - 30 * 60_000).toISOString(),
    turns: 22,
    test_result: 'passed',
    pr_url: 'https://github.com/acme/api-server/pull/54',
  },
  {
    id: 'run-004',
    issue_number: 15,
    issue_title: 'Update README with new API endpoints',
    repo: 'acme/docs',
    status: 'queued',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    started_at: new Date().toISOString(),
    turns: 0,
  },
  {
    id: 'run-005',
    issue_number: 99,
    issue_title: 'Migrate database schema to v3',
    repo: 'acme/webapp',
    status: 'failed',
    provider: 'openai',
    model: 'gpt-4o',
    started_at: new Date(Date.now() - 20 * 60_000).toISOString(),
    turns: 8,
    test_result: 'failed',
  },
]

export const MOCK_SSE_EVENTS: SSEEvent[] = [
  {
    type: 'log',
    timestamp: new Date(Date.now() - 5 * 60_000).toISOString(),
    prefix: 'INFO',
    content: 'Cloning repository acme/webapp...',
  },
  {
    type: 'log',
    timestamp: new Date(Date.now() - 4 * 60_000).toISOString(),
    prefix: 'INFO',
    content: 'Analyzing issue #42: Add dark mode toggle to settings page',
  },
  {
    type: 'turn',
    timestamp: new Date(Date.now() - 3 * 60_000).toISOString(),
    prefix: 'T·01',
    content: 'Reading src/components/Settings.tsx to understand current structure',
  },
  {
    type: 'turn',
    timestamp: new Date(Date.now() - 2 * 60_000).toISOString(),
    prefix: 'T·02',
    content: 'Creating ThemeContext provider with dark/light toggle support',
  },
  {
    type: 'test',
    timestamp: new Date(Date.now() - 1 * 60_000).toISOString(),
    prefix: 'OK',
    content: 'All 23 tests passed (4 new, 19 existing)',
  },
  {
    type: 'status',
    timestamp: new Date().toISOString(),
    prefix: 'DONE',
    content: 'PR #43 opened — ready for review',
  },
  {
    type: 'log',
    timestamp: new Date(Date.now() - 90_000).toISOString(),
    prefix: 'WARN',
    content: 'Deprecated API usage detected in Settings.tsx:42',
  },
]
